name: build

on:
    push:
      branches:
      - master

jobs:

  run_example:    
    name: run_example
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: run GreetGrpc
      run: |
        dotnet build -c Release --source https://api.nuget.org/v3/index.json /home/runner/work/FluentGrpc.Gateway/FluentGrpc.Gateway/example/GreetGrpc/GreetGrpc.csproj 
        dotnet /home/runner/work/FluentGrpc.Gateway/FluentGrpc.Gateway/example/GreetGrpc/bin/release/netcoreapp3.1/GreetGrpc.dll
    - name: run CalculateGrpc
      run: |
        dotnet build -c Release --source https://api.nuget.org/v3/index.json /home/runner/work/FluentGrpc.Gateway/FluentGrpc.Gateway/example/CalculateGrpc/CalculateGrpc.csproj
        dotnet /home/runner/work/FluentGrpc.Gateway/FluentGrpc.Gateway/example/CalculateGrpc/bin/release/netcoreapp3.1/CalculateGrpc.dll
    - name: run ExampleGateway
      run: |
        dotnet build -c Release --source https://api.nuget.org/v3/index.json /home/runner/work/FluentGrpc.Gateway/FluentGrpc.Gateway/example/ExampleGateway/ExampleGateway.csproj
        dotnet /home/runner/work/FluentGrpc.Gateway/FluentGrpc.Gateway/example/ExampleGateway/bin/release/netcoreapp3.1/ExampleGateway.dll
  
  run_test:
    name: run_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200