name: Release

on:
    push:
      branches:
      - master

jobs:
  build_artifact:    
    name: Build and upload artifact
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Init Directory
      run: cd /home/runner/work/Grpc.Gateway/Grpc.Gateway/src/Grpc.Gateway/
    - name: Build Project
      run: dotnet build --configuration Release
    - name: Create Artifact
      run: dotnet pack Grpc.Gateway.sln -o /home/runner/work/nugetpkgs -c Release --no-build
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: nugetpkgs
        path: /home/runner/work/nugetpkgs  

  release_nuget:
      name: Release to Nuget
      needs: build_artifact
      runs-on: ubuntu-latest
  
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v1
          with:
            name: nugetpkgs
        - name: list nugetpkgs
          run: ls nugetpkgs
        - name: test dotnet cmd
          run: dotnet --version  
        - name: Release
          run: |
            for file in nugetpkgs/*.nupkg
            do
              dotnet nuget push $file -k ${{ secrets.NuGetAPIKey }} --skip-duplicate -s https://www.nuget.org/api/v2/package
            done