name: .NET Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'

    - name: Restore Packages
      run: nuget restore

    - name: Build Project
      run: msbuild /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}


    - name: Run UnitTest
      run: dotnet test -c $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
