name: Release

on:
  push:
    tags:
    - 'v*'

jobs:

  # build artifacts
  build_artifact:    
    name: build artifacts
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: dotnet build
      run: dotnet build /home/runner/work/FluentGrpc.Gateway/FluentGrpc.Gateway/src/FluentGrpc.Gateway.sln -c Release --source https://api.nuget.org/v3/index.json
    - name: dotnet pack
      run: dotnet pack /home/runner/work/FluentGrpc.Gateway/FluentGrpc.Gateway/src/FluentGrpc.Gateway.sln -o /home/runner/work/nuget_pkgs -c Release --no-build --source https://api.nuget.org/v3/index.json
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: nuget_pkgs
        path: /home/runner/work/nuget_pkgs  
  
  # publish packages
  publish_packages:
      name: publish packages
      needs: build_artifact
      runs-on: ubuntu-latest
  
      steps:
        - name: download artifacts
          uses: actions/download-artifact@v1
          with:
            name: nuget_pkgs
        - name: list nuget packages
          run: ls nuget_pkgs
        - name: dotnet --version
          run: dotnet --version  
        - name: push nuget packages
          run: |
            for file in nuget_pkgs/*.nupkg
            do
              dotnet nuget push $file -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://www.nuget.org/api/v2/package
              dotnet nuget push $file -k ${{ secrets.ACCESS_TOKEN }} --skip-duplicate -s https://nuget.pkg.github.com/qinyuanpei/index.json 
            done